// <auto-generated />
using System;
using Deskverse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Deskverse.Infrastructure.Migrations
{
    [DbContext(typeof(DeskverseDbContext))]
    [Migration("20261003091438_AddRotationFields")]
    partial class AddRotationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Deskverse.Core.Entities.CollectionItem", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WallpaperId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("CollectionId", "WallpaperId");

                    b.HasIndex("WallpaperId");

                    b.ToTable("CollectionItems");
                });

            modelBuilder.Entity("Deskverse.Core.Entities.ProviderConfiguration", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessfulSync")
                        .HasColumnType("TEXT");

                    b.HasKey("ProviderId");

                    b.ToTable("ProviderConfigurations");
                });

            modelBuilder.Entity("Deskverse.Core.Entities.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowVideoWallpapers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnimatedPreviewsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoCleanupEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackgroundPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheDirectory")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FirstRunComplete")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LastActiveWallpaperId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MinimizeToTray")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PauseVideoOnBattery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PauseVideoOnFullscreen")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PreferredBrightness")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("PreferredCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PreferredColors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PreferredStyles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RotationCollectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RotationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RotationIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RotationMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RunAtStartup")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StorageLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TelemetryOptIn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("Deskverse.Core.Entities.Wallpaper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attribution")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Brightness")
                        .HasColumnType("REAL");

                    b.Property<long>("CacheLastAccessTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheRelativePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DominantColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCached")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisliked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalImportPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("SafetyStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("VisualDensity")
                        .HasColumnType("REAL");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileHash");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("LastUsedAt");

                    b.HasIndex("IsCached", "CacheLastAccessTicks");

                    b.HasIndex("SourceProvider", "SourceId");

                    b.ToTable("Wallpapers");
                });

            modelBuilder.Entity("Deskverse.Core.Entities.WallpaperCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Deskverse.Core.Entities.WallpaperUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserFeedback")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WallpaperId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAt");

                    b.HasIndex("WallpaperId", "AppliedAt");

                    b.ToTable("WallpaperUsage");
                });

            modelBuilder.Entity("Deskverse.Core.Entities.CollectionItem", b =>
                {
                    b.HasOne("Deskverse.Core.Entities.WallpaperCollection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Deskverse.Core.Entities.Wallpaper", "Wallpaper")
                        .WithMany()
                        .HasForeignKey("WallpaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Wallpaper");
                });

            modelBuilder.Entity("Deskverse.Core.Entities.WallpaperUsage", b =>
                {
                    b.HasOne("Deskverse.Core.Entities.Wallpaper", "Wallpaper")
                        .WithMany("Usage")
                        .HasForeignKey("WallpaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallpaper");
                });

            modelBuilder.Entity("Deskverse.Core.Entities.Wallpaper", b =>
                {
                    b.Navigation("Usage");
                });

            modelBuilder.Entity("Deskverse.Core.Entities.WallpaperCollection", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
